---
output: github_document
--- 

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Resistome data analysis


<!-- badges: start -->
<!-- badges: end -->

List of participants and affiliations: 

* Leo Lahti (Team lead) 
* Nitin Bayal 
* Shivang Bhanushali 
* Pande Putu Erawijantari 
* Akewak Jeba 
* Dattatray Mongad 
* Geraldson Teneng Muluh 
* Mahkameh Salehi

## Project Goals

* Prepare the Lee et al. (2023) data set for analysis in R/Bioc and provide sufficient documentation in the Github repository. 

* Create minimal website for this project using pkgdown 

* Prepare summary of the data set to be presented on a slide set

* Create tutorial on resistome data analysis using the latest R/Bioconductor methods and release them via the Github repository (vignettes/ subfolder)

* Provide exploratory summaries of the data set using R/Bioc methods

* Replicate of some key results from the manuscript using R/Bioconductor methods to verify the data

* Consider automation of specific analysis or visualization methods as functions that can be share via new R pkg, or existing packages

* Polish the data analysis workflow/s & documentation so that they can be used as training material on resistome analyses using R/Bioconductor


## Approach

### Tasks

1. Everyone - read the [publication](https://www.nature.com/articles/s41467-023-36633-7) and explore the R data (https://github.com/microbiome/data/tree/main/Lee2023)

2. Leo (antagomir - conveys scientific objetives and coordinates tasks)

3. Muluh (Daenarys8 - coordinates software installation and data acquisition, manages version control and the team’s GitHub repository, troubleshoots technical issues with tech support)

    a. Migrate the data to the codeathon repo data/ subfolder
    b. Create minimal website for this project using pkgdown

4. Nitin (nixonbyl)
ensures that all work is documented, manages GitHub README and Team Report

    a. Prepare flow diagram & README in codeathon repo (see “overall plan” above)

5. Datta (microDM)
ensures that all work is documented, manages GitHub README and Team Report

    a. Compile 3 minute presentation about the plans & present in the evening
    b. Use the flow diagram (from Nitin), and data set summary (from Mahkameh)

6. Jeba (ake123; coordinates software installation and data acquisition, manages version control and the team’s GitHub repository, troubleshoots technical issues with tech support)

    a. Support Muluh in the tasks listed above (but he can coordinate)

7. Mahkameh
fills various roles and assumes responsibilities for tasks as needed

    a. Prepare a short summary of a few slides on the study and data set to be presented on a slide set

8. Shivang (ShivangPB)
fills various roles and assumes responsibilities for tasks as needed

    a. Support Mahkameh in preparing the data set summary


## Results

## Future Work

## NCBI Codeathon Disclaimer

This software was created as part of an NCBI codeathon, a
hackathon-style event focused on rapid innovation. While we encourage
you to explore and adapt this code, please be aware that NCBI does not
provide ongoing support for it.

For general questions about NCBI software and tools, please visit: [NCBI
Contact Page](https://www.ncbi.nlm.nih.gov/home/about/contact/)


